"""config_indexes_in_users_and_projects_tables

Revision ID: bab357303b52
Revises: 4131c1d7f526
Create Date: 2023-07-08 22:05:51.606814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab357303b52'
down_revision = '4131c1d7f526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_users_login')
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_login'))
        batch_op.create_index('ix_users_login', ['login'], unique=False)
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    # ### end Alembic commands ###
