"""delete_project_name_index

Revision ID: d46990378d2c
Revises: bab357303b52
Create Date: 2023-07-08 23:15:28.001155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46990378d2c'
down_revision = 'bab357303b52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_name', ['name'], unique=False)

    # ### end Alembic commands ###
